language: python
addons:
  apt:
    packages:
     # mecab-related packages for Japanese NLP support
     - libmecab-dev
     - mecab
     - mecab-ipadic-utf8
python:
 - "3.4"
 - "3.5"
 - "3.6"
install:
 - pip install -r requirements.txt
 - pip install -r test_requirements.txt
 - python download_corpora.py
script:
  - coverage run --source newspaper tests/unit_tests.py
after_success:
  coveralls
